name: acquired_flutter
description: Flutter library for Acquired payments
version: 0.0.1
author: Vlad Bonta
homepage: https://github.com/VladBontaValentin/acquired_flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
